### ISSUE TITLE
TCP traceroute is bailing out with address in use error

### ISSUE THREAD

**Issue by Ancillius** [traviscross/mtr#304]
Compiled todays git master:

~/projects/mtr [master]
$ sudo mtr HOSTNAME -T -t

Still gives mtr: Address in use after 29-30 tries

Same as in https://github.com/traviscross/mtr/issues/275

**Comment by rewolff** [comment]
I ran over 10000 probes, with over 3000 packets lost and did not run into the problem. You are not providing me with enough information to reproduce this. 
```
                                                             My traceroute  [v0.92.20-f6b1]
getafix (192.168.234.47)                                                                                                        2019-07-10T14:14:22+0200
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                                                                                Packets               Pings
 Host                                                                                                         Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. AS???    abra2.bitwizard.nl (192.168.234.34)                                                              89.4%  1032    0.4 570.0   0.2 7015. 1835.
 2. AS???    192.168.1.254 (192.168.1.254)                                                                    89.1%  1032    0.8 492.5   0.4 7016. 1737.
 3. AS???    192.168.178.1 (192.168.178.1)                                                                    29.4%  1032    1.5 200.9   0.6 7086. 1027.
 4. (waiting for reply)
 5. (waiting for reply)
 6. AS33915  asd-tr0021-cr101-be156-2.core.as33915.net (213.51.5.38)                                          30.7%  1032   11.4 157.7   8.3 7036. 916.1
 7. AS33915  nl-ams14a-ri1-ae51-0.aorta.net (213.51.64.186)                                                   30.4%  1032   17.7 129.4   8.6 7042. 760.0
 8. AS15169  74.125.146.228 (74.125.146.228)                                                                  30.1%  1032   14.0 155.1   8.8 7040. 879.1
 9. AS15169  108.170.241.225 (108.170.241.225)                                                                30.2%  1032   16.9 185.0   7.6 7065. 972.7
    AS15169  108.170.241.193 (108.170.241.193)
10. AS15169  172.253.66.187 (172.253.66.187)                                                                  29.8%  1031   15.0 203.7   9.2 7032. 1001.
    AS15169  172.253.66.185 (172.253.66.185)
11. AS15169  sof01s11-in-f110.1e100.net (216.58.208.110)                                                      29.7%  1031   13.1 240.6   6.4 7034. 1113.

```

**Comment by blodone** [comment]
i also got this:
```
./mtr -rT 8.8.8.8 
Start: 2019-07-10T14:52:40+0200
HOST: deb-ada                     Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- _gateway                   0.0%     3    0.8   0.8   0.8   0.9   0.1
  2.|-- 87.122.185.97              0.0%     3    1.4   1.5   1.4   1.5   0.1
  3.|-- 125-199-142-46.pool.kieln  0.0%     3    5.0   5.1   4.7   5.6   0.5
  4.|-- 62.214.37.130              0.0%     3    6.3   5.8   5.2   6.3   0.8
  5.|-- ???                       100.0     2    0.0   0.0   0.0   0.0   0.0
./mtr: Address in use
```

**Comment by rewolff** [comment]
And I get: 
```
getafix:~/mtr# ./mtr -rT 8.8.8.8 
Start: 2019-07-10T15:13:30+0200
HOST: getafix                     Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- abra2.bitwizard.nl         0.0%    10    0.4   0.3   0.2   0.4   0.1
  2.|-- 192.168.1.254              0.0%    10    0.5   0.5   0.4   0.6   0.1
  3.|-- 192.168.178.1              0.0%    10    0.8   0.8   0.7   0.9   0.1
  4.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  5.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  6.|-- asd-tr0021-cr101-be156-2.  0.0%    10   12.2  12.3  10.0  19.0   3.1
  7.|-- nl-ams14a-ri1-ae51-0.aort  0.0%    10   11.3  15.0  10.8  32.9   6.6
  8.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
getafix:~/mtr# 
```

**Comment by blodone** [comment]
a better log output would help:
- which address is in use?
- which port is in use?

**Comment by Ancillius** [comment]
I am sorry to come back that late... but the issue vanished on the same compiled version.

So it seems there as an underlaying library that hat the real issue here.

Since the package in Debian Sid has been upgraded to 0.93 its not an issue for me anymore to compile the version git itself. 

But i just did and all seems fine:

$ sudo ./mtr ebookwm.com -T -t
[...]
12. ebwm1.ebookwm.de 0.0%    157   26.5  27.4  17.2  52.2   6.1
                                                                                                                                                                                                     
I cannot reproduce the issue anymore.

**Comment by thexder1** [comment]
I have had this issue constantly for the past 2+ years across all mtr versions I have used including the version I just compiled from git today. If maybe I could lock mtr to a port that does not get taken by something else, or at least get a log showing which port was in use that would be great. Until I can get better logging I do not think I would be able to provide any more information on the issue. Also it does not seem to matter what command line flags I use it will eventually quit with error saying address in use.

**Comment by bryanyork** [comment]
I have this problem as well, if you run mtr in report form in short succession, the existing TCP socket is still open and either in a FIN_WAIT1 or CLOSE_WAIT state. Waiting a while for the connection to fully close gets around this. Are we not closing the TCP socket when we exist mtr? Can we reuse an existing connection when we reload (for reporting)? If I run this in curses mode only once and leave it open it's fine.

@rewolff do these steps help you reproduce?

`root@metrics:~/mtr-latest/mtr# mtr --tcp --report google.com
Start: 2020-03-28T00:44:00-0700
HOST: metrics                     Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 96.120.88.XXX              0.0%    10    9.3   7.9   4.5  12.0   2.8
  2.|-- be-10021-rur01.santaclara  0.0%    10   12.9  10.1   4.6  12.9   3.0
  3.|-- be-232-rar01.santaclara.c  0.0%    10   12.4   9.5   4.5  12.6   3.2
  4.|-- be-299-ar01.santaclara.ca  0.0%    10    5.2   9.4   5.2  16.3   3.1
  5.|-- 96.112.146.22              0.0%    10    9.3   9.3   6.9  15.4   3.0
  6.|-- 108.170.226.50             0.0%    10   15.7  12.3   8.9  16.9   2.6
  7.|-- 72.14.239.43               0.0%    10   14.0   8.8   6.3  14.1   2.8
  8.|-- sfo07s16-in-f14.1e100.net  0.0%    10   12.5   9.3   4.8  13.3   2.7
root@metrics:~/mtr-latest/mtr# mtr --tcp --report google.com
Start: 2020-03-28T00:44:16-0700
HOST: metrics                     Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  2.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  3.|-- be-232-rar01.santaclara.c 90.0%    10  260.5 260.5 260.5 260.5   0.0
  4.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  5.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  6.|-- 137.221.68.93             90.0%    10  4526. 4526. 4526. 4526.   0.0
  7.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  8.|-- sfo07s16-in-f78.1e100.net  0.0%    10   10.8  13.1   7.7  24.0   6.0
root@metrics:~/mtr-latest/mtr# mtr --tcp --report google.com
Start: 2020-03-28T00:44:32-0700
HOST: metrics                     Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  2.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  3.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  4.|-- be-3651-cr02.sunnyvale.ca 80.0%    10  1345. 1611. 1345. 1876. 375.1
  5.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  6.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  7.|-- 24.105.30.159             90.0%    10  3654. 3654. 3654. 3654.   0.0
  8.|-- sfo07s16-in-f78.1e100.net  0.0%    10    8.6   8.6   4.2  12.0   3.1`

**Comment by martinetd** [comment]
I have the same problem here btw (`mtr 0.92` on fedora 32), rebooting "fixes" it but once I started having the problem it won't go.

So according to strace and after some messing around there are two places that can fail; either on bind:
```
3997147 bind(13, {sa_family=AF_INET, sin_port=htons(33012), sin_addr=inet_addr("10.17.42.75")}, 16) = -1 EADDRINUSE (Address already in use)
```
This one doesn't seem to fix itself with time, I've had it for over 1h and changing the destination for mtr doesn't help (the IP is my local IP obviously).
I don't see anything in `ss -na` about this port, not sure why the kernel says it's in use...


Or on connect:
```
52316 bind(8, {sa_family=AF_INET, sin_port=htons(33006), sin_addr=inet_addr("10.42.17.100")}, 16) = 0
52316 connect(8, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("1.1.1.1")}, 16) = -1 EADDRNOTAVAIL (Cannot assign requested address)
```
For this one I can see it as `TIME-WAIT` as suggested previously:
```
[root@f0 ~]# ss -na | grep 1.1.1.1
tcp               TIME-WAIT              0                   0                                                            10.42.17.100:33006            1.1.1.1:80
```
And waiting a bit makes it work again (when the entry expires); this on I can't seem to reproduce with all destinations but running report multiple times seems to make it happen.

I couldn't make the first one happen again unfortunately so no idea how to reproduce... Since I'm not sure what happens really I don't know what to suggest.

Either way, there are probably a couple of solutions:
 - set `SO_REUSEADDR` (or maybe `SO_REUSEPORT`?) might fix some cases
 - or just check the return value (return `-1` + errno == `EADDRINUSE` for bind  or `EADDRNOTAVAIL` for connect, and close socket/retry)

I'm not too confident about the first one but would be happy to submit a PR for the second pattern if you'd like.
Thanks!

**Comment by martinetd** [comment]
Well, it looks like both are properly handled in git (as per 2nd suggestion), so yes this has been fixed since 0934883fe1455e9e63ad978451bbeba3d37cf9b1 (Jul 2019); there has been one release since so nothing to ask from me I'll go try to update the package on my distro :)
Please close the issue.

**Comment by rewolff** [comment]
I can comply with such requests. Thanks for the legwork!  
:-)

**Comment by voxsoftware** [comment]
Compiled today from git, and still same error

**Comment by chriscz** [comment]
I've also come across this issue and the problem did not lie in the `mtr` binary bit the `mtr-packet` binary. I replaced only mtr first and it still popped up (doh, I didn't realize there were two!) and consequently I still hit the error because that old binary was on my path. 

Looks like it's fixed in the git version.

@voxsoftware Were you testing directly out of the repo? Because maybe the old `mtr-packet` was still on your PATH?

**Comment by Athanasius** [comment]
> Were you testing directly out of the repo? Because maybe the old `mtr-packet` was still on your PATH?

This seems key.  After a git clone/install/run explicitly /usr/local/sbin/mtr I was still seeing this.  But if I `PATH=/usr/local/sbin /usr/local/sbin/mtr ...`  then it appears to work without issue.

Annoyingly you can't strace this as a normal user to see if that gives any clues as you end up hitting:

```
Failure to open IPv4 sockets: Operation not permitted
Failure to open IPv6 sockets: Operation not permitted
/usr/local/sbin/mtr: Failure to start mtr-packet: Invalid argument
```
presumably due to some security checks with tracing.  And then when I did the strace as root ... no issue seen.

**Comment by rewolff** [comment]
Just to explain the security issues... 
MTR needs to send "weird" packets that you can't send using the normal OS interfaces. Back in the days, programs like "rlogin" would have an originating host that would vouch: "I the computer XYZ vouch for the fact that this user is called ABC and would like to login to computer UVW". Computer UVW could be configured to accept such vouching from computer XYZ. 

When you can send arbitrary packets, you can spoof such vouching from a computer. Or even pretend to be another computer who UVW is configured to trust! 

So computers normally refuse to allow arbitrary programs to send arbitrary packets. (even if you're not gaining privileges by spoofing another user or computer, you can still break other connections and stuff like that!). 

So: Sending arbitrary packets is a privilege that the OS reserves for specially crafted programs that "obey the rules themselves" like "ping", "traceroute" and "mtr-packet".  
(mtr was rewritten to separate the "special" stuff (mtr-packet) from the non-special stuff (GUI) (mtr) to prevent a bug in the gui part from allowing people access to the privileged stuff.) .

**Comment by chrisinmtown** [comment]
Please post the mtr version that got the fix. On my mac laptop brew installed mtr version `0.95` which seems to work fine. On a RHEL machine version `0.92` exhibits the `address in use` problem. Thanks in advance.

**Comment by martinetd** [comment]
https://github.com/traviscross/mtr/commit/0934883fe1455e9e63ad978451bbeba3d37cf9b1 I linked above is in v0.93.
